services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - backend-deployment:/var/www/nedellec-julien.fr/backend
      - ./uploads:/app/uploads

volumes:
  backend-deployment:
