version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env # Assurez-vous que le fichier .env est dans le même répertoire
    ports:
      - '3000:3000'
